[build]
  publish = "."

# Force HTTPS and add trailing slash fallback
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/es"
  to = "/es/index.html"
  status = 301

